/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "d1f2d15b36f6a6a9d199581b998a7ca924a1f1a8-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
